feat: Support new provider.iam property
functionalone/serverless-iam-roles-per-function pull request #75
Opened 2021-03-19 11:19 UTC by LironEr

Support the new `provider.iam` property (serverless >= [v2.4.0](https://github.com/serverless/serverless/blob/master/CHANGELOG.md#2240-2021-02-16))

Closes #73

2021-03-19 14:53 UTC, Enase requested changes

2021-03-19 14:53 UTC, Enase commented on src/lib/index.ts
> +      ? this.serverless.service.provider.iam.role?.statements
[Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) has been added in [node v14](https://nodejs.org/uk/blog/release/v14.0.0/), but plugin requires  [nodev10](https://github.com/LironEr/serverless-iam-roles-per-function/blob/feat/support_new_iam_structure/package.json#L6) and moreover readme says `Note: Node 6.10 or higher runtime required.` I believe we should fix it to require the same version everywhere.

2021-03-19 14:57 UTC, Enase approved these changes

2021-03-19 20:07 UTC, Enase commented
@LironEr CI errored in some reason. Could you restart it the build?

2021-03-20 09:17 UTC, LironEr commented
> @LironEr CI errored in some reason. Could you restart the build?

I dont think I have permissions to restart

2021-03-20 14:30 UTC, Enase commented
@LironEr Consider to do any commit+push, like replace
```
// Since serverless 2.24.0 processInput function doesn't exists
```
with
```
// Since serverless 2.24.0 processInput function doesn't exist
```

2021-03-22 14:30 UTC, merged

2021-03-22 14:31 UTC, Enase commented
@LironEr Thanks for your effort!

2021-04-06 20:57 UTC, chris-erickson commented
Can we get a NPM release to match?  Thanks!!

2021-04-16 02:28 UTC, Android3000 commented
It looks like this is currently available via serverless-iam-roles-per-function@next

@LironEr  / @Enase When would this go out as the full latest release? Thank you for this improvement!

2021-04-16 17:13 UTC, Enase commented
> When would this go out as the full latest release?

@glicht  @Android3000 There is a trouble with it https://github.com/functionalone/serverless-iam-roles-per-function/pull/62#issuecomment-821317895

2021-04-17 00:08 UTC, Enase commented
@glicht / @LironEr I've created PR from `master` branch https://github.com/functionalone/serverless-iam-roles-per-function/pull/78 feel free to review / approve / merge.